[package]
name = "mikasa"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
daemonize = "0.5.0"
dir = "0.1.2"
dirs = "6.0.0"
eframe = "0.31.1"
epaint = "0.31.1"
litcrypt = "0.4.0"
metamorph = "1.0.1"
rand_core = "0.9.3"
walkdir = "2.5.0"
