[package]
name = "mikasa"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
batnet = "1.1.1"
dirs = "6.0.0"
eframe = "0.31.1"
epaint = "0.31.1"
litcrypt = "0.4.0"
rand_core = "0.9.3"
walkdir = "2.5.0"
